# // TODO: Implementar el docker-compose
services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    networks:
      - libreria-network
    restart: unless-stopped

networks:
  libreria-network:
    driver: bridge